import { ArrowDown, ArrowUp, Columns2, Crop, EyeOff, Film, Image, Layers3, Merge, Plus, RotateCcw, Scissors, SlidersHorizontal, Trash2 } from 'lucide-react';
import type { EditorAsset } from '../../shared/types';
import type { AudioPolicy, DurationPolicy, FitMode, FrameFormat, OutputAspect, Quality } from '../../shared/editorTypes';
import type { EditorAction, EditorState } from '../editor/editorState';

const tabs = [
  ['timeline', 'Camadas', Layers3], ['cut', 'Cortar', Scissors], ['merge', 'Mesclar', Merge], ['side-by-side', 'Lado a lado', Columns2],
  ['crop', 'Crop', Crop], ['frame', 'Frame', Image], ['gif', 'GIF', Film], ['adjustments', 'Ajustes', SlidersHorizontal]
] as const;
const clock = (seconds: number) => `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(Math.floor(seconds % 60)).padStart(2, '0')}.${String(Math.floor(seconds * 100) % 100).padStart(2, '0')}`;

type Props = { state: EditorState; selected?: EditorAsset; error: string; dispatch: (action: EditorAction) => void; onExport: () => void; exporting: boolean };

export function ToolInspector({ state, selected, error, dispatch, onExport, exporting }: Props) {
  const scopedRanges = state.ranges.filter((range) => range.assetId === selected?.id);
  const mergeAssets = state.mergeOrder.map((id) => state.assets.find((asset) => asset.id === id)).filter(Boolean) as EditorAsset[];
  const selectedTrack = state.tracks.find(({ id }) => id === state.selectedTrackId);
  const selectedClip = state.tracks.flatMap(({ clips }) => clips).find(({ id }) => id === state.selectedClipId);
  const selectedClipAsset = state.assets.find(({ id }) => id === selectedClip?.assetId);
  const setCropAspect = (aspect: number) => {
    if (!selected) return;
    const sourceAspect = selected.width / selected.height;
    if (sourceAspect > aspect) {
      const width = aspect / sourceAspect;
      dispatch({ type: 'set-crop', crop: { x: (1 - width) / 2, y: 0, width, height: 1 } });
    } else {
      const height = sourceAspect / aspect;
      dispatch({ type: 'set-crop', crop: { x: 0, y: (1 - height) / 2, width: 1, height } });
    }
  };
  return <aside className="tool-inspector" aria-label="Ferramentas">
    <div className="panel-heading"><strong>Ferramentas</strong><SlidersHorizontal /></div>
    <div className="tool-tabs" role="tablist">{tabs.map(([id, label, Icon]) => <button type="button" role="tab" aria-selected={state.tab === id} key={id} onClick={() => dispatch({ type: 'set-tab', tab: id })}><Icon />{label}</button>)}</div>
    <div className="inspector-body">
      {state.tab === 'timeline' && <section>
        <h2>Composição em camadas</h2>
        <p>A faixa superior vence. Lacunas e clipes ocultos revelam automaticamente as faixas abaixo.</p>
        <button className="outline-action" type="button" onClick={() => dispatch({ type: 'add-timeline-track' })}><Plus /> Adicionar faixa</button>
        <div className="layer-priority-list">{state.tracks.map((track, index) => <div className={track.id === state.selectedTrackId ? 'selected' : ''} key={track.id}>
          <button type="button" onClick={() => track.clips[0] && dispatch({ type: 'select-timeline-clip', trackId: track.id, clipId: track.clips[0].id })}><span>P{index + 1}</span><strong>{track.name}</strong><small>{track.clips.length} clipe{track.clips.length === 1 ? '' : 's'}</small></button>
          <button type="button" aria-label={`Subir ${track.name}`} disabled={index === 0} onClick={() => dispatch({ type: 'reorder-timeline-track', trackId: track.id, direction: -1 })}><ArrowUp /></button>
          <button type="button" aria-label={`Descer ${track.name}`} disabled={index === state.tracks.length - 1} onClick={() => dispatch({ type: 'reorder-timeline-track', trackId: track.id, direction: 1 })}><ArrowDown /></button>
        </div>)}</div>
        {selectedClip && selectedTrack && <div className="selected-layer-clip">
          <div><span>Clipe selecionado</span><strong>{selectedClipAsset?.name ?? 'Mídia indisponível'}</strong></div>
          <NumberField label="Posição na timeline" value={selectedClip.timelineStart} onChange={(timelineStart) => dispatch({ type: 'move-timeline-clip', clipId: selectedClip.id, trackId: selectedTrack.id, timelineStart })} />
          <div className="field-pair"><NumberField label="Fonte: entrada" value={selectedClip.sourceStart} onChange={(sourceStart) => dispatch({ type: 'trim-timeline-clip', clipId: selectedClip.id, edge: 'start', time: selectedClip.timelineStart + sourceStart - selectedClip.sourceStart })} /><NumberField label="Fonte: saída" value={selectedClip.sourceEnd} onChange={(sourceEnd) => dispatch({ type: 'trim-timeline-clip', clipId: selectedClip.id, edge: 'end', time: selectedClip.timelineStart + sourceEnd - selectedClip.sourceStart })} /></div>
          <label className="check"><input type="checkbox" checked={selectedClip.enabled} onChange={(event) => dispatch({ type: 'set-timeline-clip-enabled', clipId: selectedClip.id, enabled: event.target.checked })} /> Clipe visível</label>
          <button type="button" onClick={() => dispatch({ type: 'hide-timeline-interval', trackId: selectedTrack.id, start: state.markIn, end: state.markOut })}><EyeOff /> Ocultar intervalo I/O</button>
        </div>}
        <label><span>Transição</span><select aria-label="Transição" value={state.timelineTransition.type} onChange={(event) => dispatch({ type: 'set-timeline-transition', value: event.target.value === 'dissolve' ? { type: 'dissolve', duration: .5 } : { type: 'none', duration: 0 } })}><option value="none">Corte seco</option><option value="dissolve">Dissolver</option></select></label>
        <label><span>Duração da transição</span><select aria-label="Duração da transição" disabled={state.timelineTransition.type === 'none'} value={state.timelineTransition.duration} onChange={(event) => dispatch({ type: 'set-timeline-transition', value: { type: 'dissolve', duration: Number(event.target.value) as .25|.5|1 } })}><option value={.25}>0,25 s</option><option value={.5}>0,5 s</option><option value={1}>1 s</option></select></label>
      </section>}
      {state.tab === 'cut' && <section><h2>Cortar e conservar</h2><p>Marque entrada e saída. Só os trechos listados serão mantidos.</p><div className="field-pair"><label><span>Entrada</span><input aria-label="Entrada" type="number" min="0" step="0.001" value={state.markIn} onChange={(e) => dispatch({ type: 'set-markers', markIn: Number(e.target.value), markOut: state.markOut })} /></label><label><span>Saída</span><input aria-label="Saída" type="number" min="0" step="0.001" value={state.markOut} onChange={(e) => dispatch({ type: 'set-markers', markIn: state.markIn, markOut: Number(e.target.value) })} /></label></div><button className="outline-action" type="button" onClick={() => dispatch({ type: 'add-range' })}>+ Adicionar trecho</button><div className="kept-heading"><span>Trechos mantidos</span><strong>{clock(scopedRanges.reduce((sum, range) => sum + range.end - range.start, 0))}</strong></div><div className="kept-list">{scopedRanges.map((range, index) => <div key={range.id}><strong>Trecho {index + 1}</strong><span>{clock(range.start)} — {clock(range.end)}</span><div className="row-actions"><button aria-label={`Subir trecho ${index + 1}`} disabled={index === 0} onClick={() => dispatch({ type: 'move-range', id: range.id, direction: -1 })}><ArrowUp /></button><button aria-label={`Descer trecho ${index + 1}`} disabled={index === scopedRanges.length - 1} onClick={() => dispatch({ type: 'move-range', id: range.id, direction: 1 })}><ArrowDown /></button><button aria-label={`Excluir trecho ${index + 1}`} onClick={() => dispatch({ type: 'remove-range', id: range.id })}><Trash2 /></button></div></div>)}</div></section>}
      {state.tab === 'merge' && <section><h2>Mesclar vídeos</h2><p>A ordem abaixo é também a ordem da exportação.</p>{mergeAssets.map((asset, index) => <div className="clip-row" key={asset.id}><div className="clip-order"><strong>{index + 1}. {asset.name}</strong><div><button aria-label={`Subir ${asset.name}`} disabled={index === 0} onClick={() => { const next = [...state.mergeOrder]; [next[index - 1], next[index]] = [next[index], next[index - 1]]; dispatch({ type: 'set-merge-order', value: next }); }}><ArrowUp /></button><button aria-label={`Descer ${asset.name}`} disabled={index === mergeAssets.length - 1} onClick={() => { const next = [...state.mergeOrder]; [next[index], next[index + 1]] = [next[index + 1], next[index]]; dispatch({ type: 'set-merge-order', value: next }); }}><ArrowDown /></button></div></div><div className="field-pair"><label><span>Início</span><input type="number" value={state.mergeRanges[asset.id]?.start ?? 0} onChange={(e) => dispatch({ type: 'set-merge-range', assetId: asset.id, start: Number(e.target.value), end: state.mergeRanges[asset.id]?.end ?? asset.duration })} /></label><label><span>Fim</span><input type="number" value={state.mergeRanges[asset.id]?.end ?? asset.duration} onChange={(e) => dispatch({ type: 'set-merge-range', assetId: asset.id, start: state.mergeRanges[asset.id]?.start ?? 0, end: Number(e.target.value) })} /></label></div></div>)}</section>}
      {state.tab === 'side-by-side' && <section><h2>Lado a lado</h2><Select label="Mídia esquerda" value={state.sideLeftAssetId} options={state.assets.map((a) => [a.id, a.name])} onChange={(value) => dispatch({ type: 'set-side-assets', left: value, right: state.sideRightAssetId })} /><Select label="Mídia direita" value={state.sideRightAssetId} options={state.assets.map((a) => [a.id, a.name])} onChange={(value) => dispatch({ type: 'set-side-assets', left: state.sideLeftAssetId, right: value })} /><Select label="Proporção" value={state.sideBySide.aspect} options={['16:9','9:16','1:1','4:5'].map((v) => [v,v])} onChange={(value) => dispatch({ type: 'set-side-settings', value: { aspect: value as OutputAspect } })} /><Range label="Divisor" value={state.sideBySide.divider} min={.2} max={.8} step={.01} onChange={(divider) => dispatch({ type: 'set-side-settings', value: { divider } })} /><div className="field-pair"><Select label="Esquerda" value={state.sideBySide.leftFit} options={[["contain","Conter"],["cover","Preencher"]]} onChange={(leftFit) => dispatch({ type: 'set-side-settings', value: { leftFit: leftFit as FitMode } })} /><Select label="Direita" value={state.sideBySide.rightFit} options={[["contain","Conter"],["cover","Preencher"]]} onChange={(rightFit) => dispatch({ type: 'set-side-settings', value: { rightFit: rightFit as FitMode } })} /></div><div className="field-pair"><Range label="Pan E. horizontal" value={state.sideBySide.leftPanX} min={0} max={1} step={.01} onChange={(leftPanX) => dispatch({ type: 'set-side-settings', value: { leftPanX } })} /><Range label="Pan E. vertical" value={state.sideBySide.leftPanY} min={0} max={1} step={.01} onChange={(leftPanY) => dispatch({ type: 'set-side-settings', value: { leftPanY } })} /></div><div className="field-pair"><Range label="Pan D. horizontal" value={state.sideBySide.rightPanX} min={0} max={1} step={.01} onChange={(rightPanX) => dispatch({ type: 'set-side-settings', value: { rightPanX } })} /><Range label="Pan D. vertical" value={state.sideBySide.rightPanY} min={0} max={1} step={.01} onChange={(rightPanY) => dispatch({ type: 'set-side-settings', value: { rightPanY } })} /></div><Select label="Duração" value={state.sideBySide.durationPolicy} options={[["shortest","Terminar no menor"],["longest","Continuar até o maior"]]} onChange={(durationPolicy) => dispatch({ type: 'set-side-settings', value: { durationPolicy: durationPolicy as DurationPolicy } })} /><Select label="Áudio" value={state.sideBySide.audio} options={[["first","Mídia 1"],["second","Mídia 2"],["mix","Misturar"],["none","Sem áudio"]]} onChange={(audio) => dispatch({ type: 'set-side-settings', value: { audio: audio as AudioPolicy } })} /></section>}
      {state.tab === 'crop' && <section><h2>Crop</h2><p>Coordenadas proporcionais preservam o recorte em qualquer preview.</p><div className="preset-grid"><button onClick={() => setCropAspect(16 / 9)}>16:9</button><button onClick={() => setCropAspect(9 / 16)}>9:16</button><button onClick={() => setCropAspect(1)}>1:1</button><button onClick={() => setCropAspect(4 / 5)}>4:5</button></div><div className="field-grid">{(['x','y','width','height'] as const).map((key) => <label key={key}><span>{key}</span><input type="number" min="0" max="1" step="0.01" value={Number(state.adjustments.crop[key].toFixed(4))} onChange={(e) => dispatch({ type: 'set-crop', crop: { ...state.adjustments.crop, [key]: Number(e.target.value) } })} /></label>)}</div><button type="button" onClick={() => dispatch({ type: 'set-crop', crop: { x: 0, y: 0, width: 1, height: 1 } })}><RotateCcw /> Tela inteira</button></section>}
      {state.tab === 'frame' && <section><h2>Extrair frame</h2><p>Tempo atual: {clock(state.currentTime)}</p><Select label="Formato" value={state.frame.format} options={['png','jpg','webp'].map((v) => [v,v.toUpperCase()])} onChange={(format) => dispatch({ type: 'set-frame', value: { format: format as FrameFormat } })} /><OutputHeight state={state} dispatch={dispatch} target="frame" /></section>}
      {state.tab === 'gif' && <section><h2>Converter para GIF</h2><div className="field-pair"><NumberField label="Início" value={state.gif.start} onChange={(start) => dispatch({ type: 'set-gif', value: { start } })} /><NumberField label="Fim" value={state.gif.end} onChange={(end) => dispatch({ type: 'set-gif', value: { end } })} /></div><NumberField label="Largura" value={state.gif.width} onChange={(width) => dispatch({ type: 'set-gif', value: { width } })} /><Range label="FPS" value={state.gif.fps} min={1} max={30} step={1} onChange={(fps) => dispatch({ type: 'set-gif', value: { fps } })} /><label className="check"><input type="checkbox" checked={state.gif.loop} onChange={(e) => dispatch({ type: 'set-gif', value: { loop: e.target.checked } })} /> Repetir continuamente</label><QualitySelect value={state.gif.quality} onChange={(quality) => dispatch({ type: 'set-gif', value: { quality } })} /></section>}
      {state.tab === 'adjustments' && <section><h2>Ajustes</h2><Select label="Rotação" value={String(state.adjustments.rotation)} options={['0','90','180','270'].map((v) => [v,`${v}°`])} onChange={(rotation) => dispatch({ type: 'set-adjustments', value: { rotation: Number(rotation) as 0|90|180|270 } })} /><label className="check"><input type="checkbox" checked={state.adjustments.flipHorizontal} onChange={(e) => dispatch({ type: 'set-adjustments', value: { flipHorizontal: e.target.checked } })} /> Espelhar horizontal</label><label className="check"><input type="checkbox" checked={state.adjustments.flipVertical} onChange={(e) => dispatch({ type: 'set-adjustments', value: { flipVertical: e.target.checked } })} /> Espelhar vertical</label><Range label="Velocidade" value={state.adjustments.speed} min={.5} max={2} step={.05} onChange={(speed) => dispatch({ type: 'set-adjustments', value: { speed } })} /><Range label="Volume" value={state.adjustments.volume} min={0} max={2} step={.05} onChange={(volume) => dispatch({ type: 'set-adjustments', value: { volume } })} /><label className="check"><input type="checkbox" checked={state.adjustments.muted} onChange={(e) => dispatch({ type: 'set-adjustments', value: { muted: e.target.checked } })} /> Remover áudio</label><OutputHeight state={state} dispatch={dispatch} target="output" /><Select label="FPS de saída" value={String(state.output.fps)} options={['0','24','25','30','60'].map((v) => [v, v === '0' ? 'Original' : v])} onChange={(fps) => dispatch({ type: 'set-output', value: { fps: Number(fps) as 0|24|25|30|60 } })} /><QualitySelect value={state.output.quality} onChange={(quality) => dispatch({ type: 'set-output', value: { quality } })} /></section>}
    </div>
    <div className="inspector-export">{error ? <p role="alert">{error}</p> : <p>Processamento local. O original não será alterado.</p>}<button className="export-button wide" type="button" disabled={Boolean(error) || exporting} onClick={onExport}>{exporting ? 'Preparando…' : state.tab === 'frame' ? 'Extrair frame' : state.tab === 'gif' ? 'Exportar GIF' : 'Exportar MP4'}</button></div>
  </aside>;
}

function Select({ label, value, options, onChange }: { label: string; value: string; options: string[][] | readonly (readonly string[])[]; onChange: (value: string) => void }) { return <label><span>{label}</span><select value={value} onChange={(e) => onChange(e.target.value)}>{options.map(([id,name]) => <option value={id} key={id}>{name}</option>)}</select></label>; }
function NumberField({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label><span>{label}</span><input type="number" step="0.001" value={value} onChange={(e) => onChange(Number(e.target.value))} /></label>; }
function Range({ label, value, min, max, step, onChange }: { label: string; value: number; min: number; max: number; step: number; onChange: (value: number) => void }) { return <label className="range-field"><span>{label}<output>{value}</output></span><input type="range" min={min} max={max} step={step} value={value} onChange={(e) => onChange(Number(e.target.value))} /></label>; }
function QualitySelect({ value, onChange }: { value: Quality; onChange: (value: Quality) => void }) { return <Select label="Qualidade" value={value} options={[["high","Alta"],["balanced","Equilibrada"],["compact","Compacta"]]} onChange={(value) => onChange(value as Quality)} />; }
function OutputHeight({ state, dispatch, target }: { state: EditorState; dispatch: (a: EditorAction) => void; target: 'frame'|'output' }) { const value = target === 'frame' ? state.frame.height : state.output.height; return <Select label="Resolução" value={String(value)} options={['0','720','1080','1440','2160'].map((v) => [v, v === '0' ? 'Original' : `${v}p`])} onChange={(height) => target === 'frame' ? dispatch({ type: 'set-frame', value: { height: Number(height) as 0|720|1080|1440|2160 } }) : dispatch({ type: 'set-output', value: { height: Number(height) as 0|720|1080|1440|2160 } })} />; }
